services:
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    env_file:
      - ./user/.env
    volumes:
      - ./user:/usr/src/app
      - /usr/src/app/node_modules
    hostname: user
    container_name: user
    ports:
      - '9001:9001'
    depends_on:
      - rabbitmq
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    env_file:
      - ./auth/.env
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
    hostname: auth
    container_name: auth
    ports:
      - '9002:9002'
    depends_on:
      - rabbitmq
  token:
    build:
      context: ./token
      dockerfile: Dockerfile
    env_file:
      - ./token/.env
    container_name: token
    volumes:
      - ./token:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15671:15672"
