version: "3"

services:
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    hostname: user
    ports:
      - 9001:9001
    env_file:
      - ./user/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
  token:
    build:
      context: ./token
      dockerfile: Dockerfile
    hostname: token
    depends_on:
      - rabbitmq
    env_file:
      - ./token/.env
  kong:
    build:
      context: ./kong
      dockerfile: Dockerfile
    container_name: kong
    restart: on-failure
    command: "kong start"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8080
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:9000
    ports:
      - "8080:8080"
      - "9000:9000"
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: on-failure
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15671:15672"
