database:
  image: postgres:latest
  container_name: nest-postgres
  ports:
    - 5431:5432
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=master123
    - POSTGRES_DB=postgres
  volumes:
    - database:/var/lib/postgresql/data
  networks:
    - backend
rabbitmq:
  image: rabbitmq:latest
  container_name: nest-rabbitmq
  hostname: rabbitmq
  volumes:
    - /var/lib/rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  env_file:
    - .env
cache:
  image: redis:latest
  container_name: nest-redis
  restart: always
  ports:
    - "6379:6379"
  networks:
    - backend
kong:
  image: kong:latest
  container_name: kong
  restart: on-failure
  command: "kong start"
  volumes:
    - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
  environment:
    KONG_DATABASE: "off"
    KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    KONG_PROXY_LISTEN: 0.0.0.0:8080
    KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
    KONG_ADMIN_LISTEN: 0.0.0.0:9000
  ports:
    - "8080:8080"
    - "9000:9000"
  networks:
    - backend
networks:
  backend:
    driver: bridge
volumes:
  database:
    driver: local
  cache:
    driver: local
